train_path: ./dataset/Train
valid_path: ./dataset/Valid
test_path: ./dataset/Test
save_path: /content/save/
type_model: "Kmeans"
model_extract_name: "resnet34"
max_iter: 200
task: "clustering"
image_C: 3
image_W: 224
image_H: 224
num_clusters: 16
batch_size: 128
