train_path: ./dataset/Train
valid_path: ./dataset/Valid
test_path: ./dataset/Test
url_demo: https://icdn.dantri.com.vn/thumb_w/640/2021/05/27/hoa-cam-tu-cau-lang-son-8-1622082961519.jpg
save_path: /content/save/
type_model: "Kmeans"
aug: False
mini_batch: 256
model_extract_name: "resnet34"
max_iter: 10000
task: "clustering"
image_C: 3
image_W: 224
image_H: 224
num_clusters: 16
batch_size: 512
