train_path: ./dataset/Train
valid_path: ./dataset/Valid
test_path: ./dataset/Test
url_demo: https://icdn.dantri.com.vn/thumb_w/640/2021/05/27/hoa-cam-tu-cau-lang-son-8-1622082961519.jpg
save_path: /content/save/
type_model: "ResNet"
load_pretrained: True
aug: True
task: "classify"
patience: 5
image_C: 3
image_W: 224
image_H: 224
num_classes: 16
batch_size: 128
learning_rate: 0.001
num_epochs: 100
