train_path: ./dataset/Train
valid_path: ./dataset/Valid
test_path: ./dataset/Test
save_path: /content/save/
type_model: "ResNet"
model_extract_name: "resnet34"
aug: True
task: "classify"
patience: 5
image_C: 3
image_W: 224
image_H: 224
num_classes: 16
batch_size: 128
learning_rate: 0.001
num_epochs: 100
