train_path: ./content/Train
valid_path: ./content/Valid
test_path: ./content/Test
save_path: /content/save/
type_model: "Kmeans"
model_extract_name: "vgg16"
image_C: 3
image_W: 224
image_H: 224
num_classes: 16
batch_size: 128

